---
apiVersion: v1
kind: Pod
metadata:
  labels:
    env: nginx-2
  name: nginx-2
spec:
  containers:
  - image: nginx
    name: nginx-2

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-2
  labels:
    env: nginx-2
spec:
  selector:
    env: nginx-2
  type: NodePort
  ports:
  - nodePort: 32051
    port: 80
    protocol: TCP
    targetPort: 80