---
apiVersion: v1
kind: Pod
metadata:
  labels:
    env: nginx-1
  name: nginx-1
spec:
  containers:
  - image: nginx
    name: nginx-1

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-1
  labels:
    env: nginx-1
spec:
  selector:
    env: nginx-1
  type: NodePort
  ports:
  - nodePort: 32050
    port: 80
    protocol: TCP
    targetPort: 80