apiVersion: v1
kind: Pod
metadata:
  labels:
    env: mynginx
  name: mynginx
spec:
  containers:
  - image: nginx
    name: mynginx
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx
  labels:
    env: mynginx
spec:
  ports:
  - nodePort: 32057
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    env: mynginx
  type: NodePort